### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by kadoyau** [pastak/scrapbox-converter#1]
# context
https://twitter.com/kadoyau/status/853101245912891392

# log
```
❯❯❯ npm cache clean
❯❯❯ npm install -g scrapbox-converter
npm WARN deprecated babel-preset-es2015-node4@2.1.1: Use npmjs.org/babel-preset-env instead, see https://github.com/babel/babel-preset-env
/usr/local/lib
└── (empty)

npm ERR! path /usr/local/lib/node_modules/scrapbox-converter/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/scrapbox-converter/dist/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kadoyau/.npm/_logs/2017-04-15T04_51_44_272Z-debug.log
```
## environments
- OS: macOS Sierra 10.12.3
```
❯❯❯ node -v
   v7.9.0
❯❯❯ npm -v
   4.5.0
```

# FYI
The following steps work for me:
- clone this repository 
- `npm run build`
- `GYAZO_ACCESS_TOKEN=MY_ACCESS_TOKEN node dist/index.js hoge.enex > hoge.json`

**Comment by pastak** [comment]
It reproduces in my environment

**Comment by pastak** [comment]
memo: I updated package but it got `cb() never called!`

**Comment by pastak** [comment]
I update package `v.0.1.6` then you can install it. 🙇 

NOTE: I don't know why package packed with `yarn pack` (it runs in `yarn publish`) is different from `npm pack` ( via `npm publish` )

**Comment by pastak** [comment]
related yarn's issue: https://github.com/yarnpkg/yarn/issues/2851

**Comment by kadoyau** [comment]
I have just installed v.0.2.1 succesfully. Thanks!
