### ISSUE TITLE
md2sb: nested list

### ISSUE THREAD

**Issue by kdmsnr** [pastak/scrapbox-converter#51]
I've set fixtures of nested list (and, of course, tweaked simpleReteral.ts):

* fixtures/md/list-nested.md
```
* item1
    * item1-1
* item2
```

* fixtures/scrapbox/list-nested.txt
```
 item1
  item1-1
 item2
```

but actually, the test fails and it is converted like this:

```
 item1  item1-1
 item2
```

Unfortunately, It seems that nested list is not processed correctly.

**Comment by pastak** [comment]
It is a known issue but it looks solved by https://github.com/remarkjs/remark/issues/523 so I'll update `remark` and try it. I'll let you know about the result.

**Comment by pastak** [comment]
@kdmsnr I have updated remark and make md2sb supporting nested listing. Please check it out v5.1.1

**Comment by pastak** [comment]
It solves https://github.com/pastak/md2sb/issues/1 by @hashrock
