### ISSUE TITLE
Error: could not execute `scrapbox-converter` because of TypeError

### ISSUE THREAD

**Issue by yto60** [pastak/scrapbox-converter#81]
Hi, I tried to execute `scrapbox-converter` as written on [packages/scrapbox-converter/README.md](https://github.com/pastak/scrapbox-converter/blob/master/packages/scrapbox-converter/README.md#usage) to convert .md files, and got some TypeErrors.

```
$ scrapbox-converter test.md > import.json
/usr/local/lib/node_modules/scrapbox-converter/node_modules/enex2sb/dist/libs/uploadImage.js:27
const client = new Gyazo(process.env.GYAZO_ACCESS_TOKEN);
               ^

TypeError: Gyazo is not a constructor
    at Object.<anonymous> (/usr/local/lib/node_modules/scrapbox-converter/node_modules/enex2sb/dist/libs/uploadImage.js:27:16)
...
```

Changing [packages/enex2sb/src/libs/uploadImage.ts](https://github.com/pastak/scrapbox-converter/blob/master/packages/enex2sb/src/libs/uploadImage.ts#L1) as below has fixed this error.

```diff
- import * as Gyazo from 'gyazo-api';
+ import Gyazo from 'gyazo-api';
```

(FYI: When imported like `import * as Gyazo`, Gyazo is a namespace, so it could not be a constructor. [import - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_an_entire_modules_contents))

Then I tried to execute `scrapbox-converter` again, and got another TypeError.

```
$ scrapbox-converter test.md > import.json
/usr/local/lib/node_modules/scrapbox-converter/dist/command.js:20
    .usage('scrapbox-converter <...files>')
    ^

TypeError: Cannot read property 'usage' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/scrapbox-converter/dist/command.js:20:5)
...
```

This was because the description key was not set in [packages/scrapbox-converter/package.json](https://github.com/pastak/scrapbox-converter/blob/master/packages/scrapbox-converter/package.json).

Adding description to package.json or removing line 15 from [packages/scrapbox-converter/src/command.ts](https://github.com/pastak/scrapbox-converter/blob/master/packages/scrapbox-converter/src/command.ts#L15) fixed this error.

Executing `scrapbox-converter` again worked.

**Comment by pastak** [comment]
Thanks for your report. I’ll make it fix 👍

**Comment by yto60** [comment]
Thanks! I created a PR.
https://github.com/pastak/scrapbox-converter/pull/82
